---
# Variables for some custom config
# Copy File and rename to custom.yml

# support for high dpi screens
#high_dpi_fix: False
#high_dpi_factor: 200

# Double Click to open folder
# double_click_folder: True
#
# Git Config
# git_settings:
#     - { name: 'user.email', value: 'demo@gmail.com' }
#     - { name: 'user.name', value: 'demo' }
#
# Insync Client
# insync_install: True
#
#
# Ram Disk
#ram_disk_enalbed: True
#ram_disk_size: "1024M"

# Java 
# java_install: True
# java_pkg: oracle-java9-installer
# java_pkg_version:  9.0.1-1~webupd8~0 
#
#
# Google Cloud Tools
#gcloud_install: True
