---
# Miki Workstation Playbook

- name: Install Common Packages
  hosts: all
  become: True
  roles:
    - { role: common, tags: ["common"] }
    
- name: Configure Ram Disk
  hosts: all
  become: True
  roles:
    - { role: ram-disk, tags: ["ram-disk"] }
    
- name: Install VMWare Tools
  hosts: all
  become: True
  roles:
    - { role: vmware, tags: ["vmware"] }
    
- name: Configure KDE Settings
  hosts: all
  roles:
    - { role: kde, tags: ["kde"] }
    
- name: Install Java
  hosts: all
  become: True
  roles:
    - { role: java, tags: ["java"] }
    
- name: Install Docker
  hosts: all
  become: True
  roles:
    - { role: docker, tags: ["docker"] }
    
- name: Install OpenVPN
  hosts: all
  become: True
  roles:
    - { role: openvpn, tags: ["openvpn"] }
    
- name: Install Code Tools
  hosts: all
  become: True
  roles:
    - { role: code, tags: ["code"] }
    
- name: Install Server Tools
  hosts: all
  become: True
  roles:
    - { role: server, tags: ["server"] }
    
- name: Install IntelliJ
  hosts: all
  become: True
  roles:
    - { role: intellij, tags: ["intellij"] }
    
- name: Install Insync
  hosts: all
  become: True
  roles:
    - { role: insync, tags: ["insync"] }
    

