---
# Miki Workstation Playbook

- name: Install Common Packages
  hosts: all
  become: True
  roles:
    - { role: common, tags: ["common"] }

- name: Install Enpass
  hosts: all
  become: True
  roles:
    - { role: enpass, tags: ["enpass"] }

- name: Configure Ram Disk
  hosts: all
  become: True
  roles:
    - { role: ram-disk, tags: ["ram-disk"] }

- name: Install VMWare Tools
  hosts: all
  become: True
  roles:
    - { role: vmware, tags: ["vmware"] }

- name: Configure KDE Settings
  hosts: all
  roles:
    - { role: kde, tags: ["kde"] }

- name: Install Java
  hosts: all
  become: True
  roles:
    - { role: java, tags: ["java"] }

- name: Install Docker
  hosts: all
  become: True
  roles:
    - { role: docker, tags: ["docker"] }

- name: Install OpenVPN
  hosts: all
  become: True
  roles:
    - { role: openvpn, tags: ["openvpn"] }

- name: Install Code Tools
  hosts: all
  become: True
  roles:
    - { role: code, tags: ["code"] }

- name: Install Server Tools
  hosts: all
  become: True
  roles:
    - { role: server, tags: ["server"] }

- name: Install IntelliJ
  hosts: all
  become: True
  roles:
    - { role: intellij, tags: ["intellij"] }

- name: Install Kubectl
  hosts: all
  become: True
  roles:
    # we add 'when' here to avoid changing role in submodule
    - { role: kubectl, tags: ["kubectl"], when: kubectl_install }

- name: Install Mini Kube
  hosts: all
  become: True
  roles:
    # we add 'when' here to avoid changing role in submodule
    - { role: minikube, tags: ["minikube"], when: minikube_install }


- name: Install Google Cloud Tools
  hosts: all
  become: False
  roles:
    # we add 'when' here to avoid changing role in submodule
    - { role: role-install-gcloud, tags: ["gcloud"], when: gcloud_install }
