---

- name: Configure Git Settings
  become: False
  git_config: name='{{ item.name }}' scope=global value='{{ item.value }}'
  with_items: '{{ git_settings }}'
  when: git_settings is defined

- name: Install Maven
  apt: pkg=maven state=present

- name: Install Node JS
  apt: pkg=nodejs state=present
  
- name: Create Node Binary simlink for 'node' 
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Install NPM
  apt: pkg=npm state=present

# sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
#- name: Add Yarn Keyserver
#  apt_key: keyserver='pgp.mit.edu' id='D101F7899D41F3C3' state=present
  
  
- name: Add Yarn Repo
  apt_repository: repo='deb http://dl.yarnpkg.com/debian/  stable main' state=present

- name: Install Yarn
  apt: pkg=yarn state=present
  
- name: Check if Git Kranken is installed
  command: dpkg-query -W gitkraken
  register: gitkraken_check_deb
  failed_when: gitkraken_check_deb.rc > 1
  changed_when: gitkraken_check_deb.rc == 1
  
- name: Install Git Kranken Ui
  apt: deb=https://release.gitkraken.com/linux/gitkraken-amd64.deb state=present
  when: gitkraken_check_deb.rc == 1

- name: Add Atom repository
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/atom/ubuntu {{ ansible_distribution_release }} main' state=present
  when: code_atom_install == True

- name: Install Atom Editor
  apt: pkg=atom state=present update_cache=yes
  when: code_atom_install == True

- name: Install Ansible-Lint via Pip
  pip: name=ansible-lint state=present

- name: Install Atom Packages
  become: False # installs in home dir
  apm: name={{ item }} state=latest
  with_items:
    - 'linter'
    - 'minimap'
    - 'emmet'
    - 'file-icons'
    - 'php-twig'
    - 'language-docker'
  when: code_atom_install == True

- name: Ensure Code Directory Exists
  become: False
  file:
    state=directory
    mode=0755
    dest={{code_dir}}
