---

- name: Configure Git Settings
  become: False
  git_config: name='{{ item.name }}' scope=global value='{{ item.value }}'
  with_items: '{{ git_settings }}'
  when: git_settings is defined

- name: Install Maven
  apt: pkg=maven state=present

- name: Install Node JS
  apt: pkg=nodejs state=present
  
- name: Create Node Binary simlink for 'node' 
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: Add Atom repository
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/atom/ubuntu {{ ansible_distribution_release }} main' state=present
  when: code_atom_install == True

- name: Install Atom Editor
  apt: pkg=atom state=present update_cache=yes
  when: code_atom_install == True

- name: Install Ansible-Lint via Pip
  pip: name=ansible-lint state=present

- name: Install Atom Packages
  become: False # installs in home dir
  apm: name={{ item }} state=latest
  with_items:
    - 'linter'
    - 'minimap'
    - 'emmet'
    - 'file-icons'
    - 'language-docker'
  when: code_atom_install == True

- name: Ensure Code Directory Exists
  become: False
  file:
    state=directory
    mode=0755
    dest={{code_dir}}
