---

- name: Check if intellij has already been downlaoded
  stat: path={{intellij_tmp}}
  register: result_intellij_downloaded

- name: Download intellij
  get_url: url={{intellij_url}} dest={{intellij_tmp}}
  when: result_intellij_downloaded.stat.exists == False

- name: Ensure installation directory
  file:
    state=directory
    mode=0755
    dest={{intellij_install_dir}}

- name: Unarchive intellij
  unarchive:
    copy=no
    src={{intellij_tmp}}
    dest={{intellij_install_dir}}

- name: Retreive intellij dir name
  command: ls -t {{intellij_install_dir}}
  register: result_intellij_folder_name

#- name: Ensure intellij is configured
#  template: src=idea.properties.j2 dest={{intellij_install_dir}}/{{intellij_folder_name}}/bin/idea.properties

