---


- name: Check if intellij is installed
  stat: path={{intellij_install_dir}}
  register: result_intellij_installed
  when: intellij_install
  become: False

- include_tasks: install.yml
  when: intellij_install and result_intellij_installed.stat.exists == False
  become: False

- include_tasks: configure.yml
  when: intellij_install
  become: False
