
- name: add add-apt-repostory
  apt: pkg=software-properties-common state=present update_cache=yes

- name: add webupd8 ppa
  apt_repository: repo='ppa:webupd8team/java'

- name: update apt
  apt: update_cache=yes cache_valid_time=3600

- name: auto accept oracle jdk license
  shell: echo {{ java_pkg }} shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: install java
  apt: pkg={{item}} state=present
  with_items:
    - "{{ java_pkg }}={{ java_pkg_version }}"
    - ca-certificates


